#GUESS THE NUMBER RANDOMLY GENERATED BY THE COMPUTER IN 6 ATTEMPTS

# -*- coding: utf-8 -*-
"""
Created on Mon Dec 19 11:44:51 2016

@author: Nabin
"""
from random import randint

def getInputNumberfromKeyboard():
    try:
        x = int (raw_input("Enter any number to guess: "))
        return x
    except:
        print "Please enter correctly"
    
    
def getInputNumber():
    numberInput = getInputNumberfromKeyboard()
    while numberInput is None:
        numberInput = getInputNumberfromKeyboard()
    return numberInput

def randomNumberGame():

    randomNumber = randint(10,99)
    n = 5
   
    x = getInputNumber()
 
    while(n>0):
        
        if(x==randomNumber):
            print "You guessed it right"
            break
        else:
            
            if (x > randomNumber):
                print "Random Number is less than you entered"
            else:
                print "Random Number is high than you entered"
            x = getInputNumber()
        n-=1
    if (n == 0):
        print "You failed to guess. The random number was %d" %randomNumber
    
    playAgain = raw_input("Do you want to play again (y/n)? : ")
    
    if(playAgain == 'y' or playAgain =='Y'):
        randomNumberGame()
    
randomNumberGame()


    